/**
 * Texture clothing catalog — types and runtime loader.
 * Catalog data lives in public/assets/clothing/catalog.json (generated by
 * scripts/curate_texture_catalog.py). Loaded at runtime to avoid TS
 * complexity limits with large literal arrays.
 */
import type { ClothingItem } from '../types/clothing.js';

/** Body region targeted by texture clothing */
export type TextureTarget = 'upper' | 'lower' | 'head';

/** Extended ClothingItem with texture target and provenance */
export interface TextureClothingItem extends ClothingItem {
  target: TextureTarget;
  creator: string;
  source_region: string;
  license: string;
}

/** Cached catalog after first load */
let cachedCatalog: TextureClothingItem[] | null = null;

/**
 * Load the texture clothing catalog from JSON.
 * Returns cached result on subsequent calls.
 */
export async function loadTextureClothingCatalog(): Promise<TextureClothingItem[]> {
  if (cachedCatalog) return cachedCatalog;

  try {
    const resp = await fetch('assets/clothing/catalog.json');
    if (!resp.ok) {
      console.warn(`[TextureCatalog] Failed to load: ${resp.status}`);
      return [];
    }
    cachedCatalog = await resp.json() as TextureClothingItem[];
    console.log(`[TextureCatalog] Loaded ${cachedCatalog.length} texture clothing items`);
    return cachedCatalog;
  } catch (err) {
    console.warn('[TextureCatalog] Error loading catalog:', err);
    return [];
  }
}
